#!/bin/sh

case "${SRANDRD_OUTPUT} ${SRANDRD_EVENT}" in
  "HDMI1 connected") 
		notify-send "HDMI1 connected" 
		display-options
	;;
  "HDMI1 disconnected") 
		notify-send "HDMI1 disconnected"
		xrandr --output eDP1 --auto --primary
	;;
esac