#!/bin/sh

confirm() {
	confirm=$(echo -e "yes\nno" | rofi -dmenu -p "Confirm?" -bw 0 -lines 2 -separator-style none -location 0 -width 10 -hide-scrollbar -padding 5)
	[[ "$confirm" = "yes" ]] 
	return	
}

res=$(echo -e "reboot\nshutdown\nsuspend\nlock" | rofi -dmenu -p "Power Options" -bw 0 -lines 4 -width 10 -padding 5)


exit_function() {
  if hash light-locker 2>/dev/null; then
      echo 'light locker'
      light-locker-command -l
  elif hash i3msg 2>/dev/null; then
      i3msg exit
  fi
}

if [ ! -z $res ]; then
	case $res in
		reboot)
			confirm && systemctl reboot
		;;
		shutdown)
			confirm && systemctl poweroff
		;;
		suspend)
			confirm && systemctl suspend
		;;
		lock)
			confirm && exit_function
		;;
	esac
fi
